config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # resources :dashboards, only: [:show, :update]

  get "dashboards/:user_id", to: "dashboards#show", as: "dashboard"
  get 'users_personnalities/:user_id', to: "users_personnalities#show", as: "results"
  resources :users_personnalities, only: :create
  root to: 'pages#home'
  # resources :surveys, only: [:index, :show]
  resources :answers, only: [] do
    resources :users_answers, only: [:create]
  end
  resources :careers, only: [:index]
  resources :surveys, only: [:index, :show] do
    resources :attempts, only: [:new, :create, :edit, :update]
  end

  resources :training_centers, only: [:index, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attempt.rb
class Attempt < ApplicationRecord
  belongs_to :survey
  belongs_to :user
  has_many :user_answers, dependent: :destroy
end

app/models/career.rb
class Career < ApplicationRecord
  belongs_to :personality_riasec
  has_many :training_centers, dependent: :destroy
  has_many :users_personalities
  include PgSearch
  multisearchable against: [:title, :category]
  scope :find_title, lambda { |search| where("title ILIKE :search", search: "%#{search}%") }
end

app/models/global_search.rb
class GlobalSearch

  def initialize(query)
    @query = query
  end

  def result_careers
    Career.search(query)
  end

  def result_training_centers
    TrainingCenter.search(query)
  end
end

app/models/personality_riasec.rb
class PersonalityRiasec < ApplicationRecord
  has_many :success_profiles
  has_many :careers, dependent: :destroy
  has_many :users_personalities
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey
  has_many :answers, dependent: :destroy
end

app/models/success_profile.rb
class SuccessProfile < ApplicationRecord
  belongs_to :personalityriasec
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :attempts, dependent: :destroy
  has_many :questions, dependent: :destroy
end

app/models/training_center.rb
class TrainingCenter < ApplicationRecord
  belongs_to :career
  include PgSearch
  multisearchable against: [:name, :city, :category]
  scope :find_name, lambda { |search| where("name ILIKE :search", search: "%#{search}%") }
  geocoded_by :full_address
  # mount_uploader :photo, PhotoUploader
  after_validation :geocode, if: :will_save_change_to_full_address?

  def full_address
    [address, postal_code, city].compact.join(', ')
  end

  def will_save_change_to_full_address?
    will_save_change_to_address? || will_save_change_to_postal_code? || will_save_change_to_city?
  end

  private

  def training_params
    params.require(:training_centersin).permit(:photo)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :photo, PhotoUploader
  has_many :user_answers, dependent: :destroy
  has_many :attempts, dependent: :destroy
  has_many :users_personalities, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  # after_create :send_welcome_email

    #private

    #def send_welcome_email
    # UserMailer.welcome(self).deliver_now
    #end
end

app/models/user_answer.rb
class UserAnswer < ApplicationRecord
  belongs_to :answer
  belongs_to :user
  belongs_to :attempt
end

app/models/users_personality.rb
class UsersPersonality < ApplicationRecord
  belongs_to :user
  belongs_to :career, optional: true
  belongs_to :personalityriasec, optional: true
end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController
  def new
    @survey = Survey.find(params[:survey_id])
    @attempt = Attempt.create(user: current_user, survey: @survey, result: "")
    @questions = @survey.questions.where(gender: [nil, current_user.gender])
    @lastquestion = @questions.find_by(number: 8)
  end

  def update
    @attempt = Attempt.find(params[:id])
    @user = current_user
    @user_answer = UserAnswer.all.where(user_id: @user)
    @user_answers = @user_answer.where(attempt_id: @attempt)
    @user_answers.each do |answer|
      @attempt.result << answer.answer.column
    end
    calcul = []
    r = @attempt.result.count("R")
    calcul << r
    i = @attempt.result.count("I")
    calcul << i
    a = @attempt.result.count("A")
    calcul << a
    s = @attempt.result.count("S")
    calcul << s
    e = @attempt.result.count("E")
    calcul << e
    c = @attempt.result.count("C")
    calcul << c
    case calcul.max
    when calcul[0]
      result = "R"
    when calcul[1]
      result = "I"
    when calcul[2]
      result = "A"
    when calcul[3]
      result = "S"
    when calcul[4]
      result = "E"
    when calcul[5]
      result = "C"
    end
    @attempt.update(result: result)
    redirect_to results_path(current_user)
  end
end

app/controllers/careers_controller.rb
class CareersController < ApplicationController
  def index
    @careers = Career.all
    @user = current_user
    @user_personality = UsersPersonality.find_by(user_id: current_user)
    @results = PgSearch.multisearch(params[:query])
  end

  def show
    @career = Career.find(params[:id])
    @users_personalities = @career.users_personalities.where(gender: [nil, current_user.gender])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def index
    @surveys = Survey.all
  end

  def show
    @survey = Survey.find(params[:id])
    @questions = @survey.questions.where(gender: [nil, current_user.gender])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    # To uncomment when other tables will be created.
    # @training_centers = current_user.users_personalities.training_centers.where.not(latitude: nil, longitude: nil)

    # @markers = @training_centers.map do |training_center|
    #   {
    #     lng: training_center.longitude,
    #     lat: training_center.latitude
    #   }
    # end
  end
end

app/controllers/users_personnalities_controller.rb
class UsersPersonnalitiesController < ApplicationController

  def create
    @personality = params[:personality]
    @career = params[:career]
    @user = current_user
    user_personality = UsersPersonality.new(user: current_user, personality_riasec_id: @personality, career_id: @career)
    user_personality.save
    redirect_to dashboard_path(current_user)
  end

  def show
    @user = current_user
    @result = current_user.attempts.last.result
    case @result
    when "R"
      @personality_riasec = PersonalityRiasec.find_by(name: "Réaliste")
    when "I"
      @personality_riasec = PersonalityRiasec.find_by(name: "Investigateur")
    when "A"
      @personality_riasec  = PersonalityRiasec.find_by(name: "Artistique")
    when "S"
      @personality_riasec  = PersonalityRiasec.find_by(name: "Social")
    when "E"
      @personality_riasec  = PersonalityRiasec.find_by(name: "Entrepreneur")
    when "C"
      @personality_riasec  = PersonalityRiasec.find_by(name: "Conventionnel")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/users_personnalities/show.html.erb
<%= render 'shared/sidebar_menu' %>
  <div class="modal-dialog modal-lg modal-job"  id="exampleModal" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title text-center" id="exampleModalLabel">Vous avez un profil de type :</h2>
      </div>
      <div class="modal-body">
        <div class="row">
      <div class="col-md-5 py-5">
        <center>
          <%= image_tag (@personality_riasec.avatar_f), height: 320, width: 320, class: "avatar-large", alt: "avatar-large-réaliste"  %>
        </center>
      </div>
      <div class="col-md-7">
        <h3><strong><%= @personality_riasec.name %></strong></h3>
        <div class="well">
          <h4 class="small" style="color: #36b9cc"><strong><i class="fas fa-plus"></i> Vos points forts</strong></h4>
        <%= @personality_riasec.points_forts %>
         </div>
         <div class="well">
          <h4 class="small" style="color: #e74a3b"><strong><i class="fas fa-minus"></i> Vos points faibles</strong></h4>
        <%= @personality_riasec.points_faibles %>
        </div>
        <div class="well">
          <span class="badge badge-pill badge-danger" style="background-color: darkgray !important;">Patient</span>
          <span class="badge badge-pill badge-danger" style="background-color: darkgray !important;">Minitieux</span>
          <span class="badge badge-pill badge-danger" style="background-color: darkgray !important;">Franc</span>
        </div>
      </div>
    </div>
      <div class="modal-footer">
        <button id="randomize-career" type="button" class="btn btn-lg btn-info">Plus de métiers</button>
      </div>
    <div class="row" style="padding-top:20px;">
      <% @personality_riasec.careers.sample(3).each do |career| %>
        <div class="col-md-4">
          <%= link_to users_personnalities_path(personality: @personality_riasec, career: career), method: :post do %>
            <div class="card job">
              <div class="card-body">
                <h5 class="card-title">Métier</h5>
                <p class="card-text">
                  <div url(h)">
                    <strong><%= career.title %></strong>
                  </div>
                </p>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
     </div>
    </div>
  </div>
        </div>
       </div>
    </div>
  </div> -->
<body style="background:#123;">