config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # resources :dashboards, only: [:show, :update]

  get "dashboards/:user_id", to: "dashboards#show", as: "dashboard"
  get 'users_personnalities/:user_id', to: "users_personnalities#show", as: "results"
  resources :users_personnalities, only: :create
  root to: 'pages#home'
  # resources :surveys, only: [:index, :show]
  resources :answers, only: [] do
    resources :users_answers, only: [:create]
  end
  resources :careers, only: [:index]
  resources :surveys, only: [:index, :show] do
    resources :attempts, only: [:new, :create, :edit, :update]
  end

  resources :training_centers, only: [:index, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/career.rb
class Career < ApplicationRecord
  belongs_to :personality_riasec
  has_many :training_centers, dependent: :destroy
  has_many :users_personalities
  include PgSearch
  multisearchable against: [:title, :category]
  scope :find_title, lambda { |search| where("title ILIKE :search", search: "%#{search}%") }
end

app/controllers/careers_controller.rb
class CareersController < ApplicationController
  def index
    @careers = Career.all
    @user = current_user
    @user_personality = UsersPersonality.find_by(user_id: current_user)
    @results = PgSearch.multisearch(params[:query])
  end

  def show
    @career = Career.find(params[:id])
    @users_personalities = @career.users_personalities.where(gender: [nil, current_user.gender])
  end
end

app/views/careers/index.html.erb
<%= render 'shared/navbar' %>
<div class="wrapper">
    <!-- Sidebar  -->
    <nav id="sidebar">
        <div class="text-center sidebar-header">
          <%= image_tag @user_personality.career.personality_riasec.avatar_f, class: "avatar-large", alt: "avatar-large" %>
          <p class="text-center small"><%= @user_personality.career.personality_riasec.name %></p>
          <p class="text-center" id="career"><%= @user_personality.career.title %></p>
        </div>
      <ul class="list-unstyled CTAs">
      <li>
       <%= link_to "Refaire le test", new_survey_attempt_path(Survey.last), class: "btn-warning"%>
      </li>
      </ul>

        <ul class="list-unstyled CTAs components">
            <li class="active">
            <li>
              <%= link_to "Ma personnalité", results_path(current_user) %>
            </li>
                   <li>
                      <%=  link_to "Gérer mon profil", edit_user_registration_path  %>
                    </li>
            </li>
        </ul>
  </nav>
<!----SideNavbar----->
    <!-- Page Content -->
    <div id="content-search">
      <h2 class="search-title">Vous trouverez ici une liste de métiers et de centres de formation associés à votre recherche : <strong>"<%= params[:query] %>" </strong></h2>
      <div class="grid-search">
        <div class="cards-search">
          <div class="card-search">
            <% @results.each do |result| %>
              <% if result.searchable_type == "TrainingCenter" %>
                <div class="card-dashboard-search">
                  <div class="card-category-search training badge-info">CENTRE DE FORMATION</div>
                    <div class="card-description-search">
                      <h2> <%= result.searchable.name %> </h2>
                      <p><strong><i class="fas fa-map-marker-alt"></i></strong> <%= result.searchable.address %>, <%= result.searchable.city %></p>
                      <p><strong><i class="fas fa-at"></i></strong> <%= link_to "Site-web", result.searchable.website , :target => "_blank" %> </p>
                    </div>
                  </div>
                <% else %>
                <div class="card-dashboard-search">
                  <div class="card-category-search career badge-info">MÉTIER</div>
                    <div class="card-description-search">
                      <h2><strong><i class="fas fa-graduation-cap"></i></strong> <%= result.searchable.title %></h2>
                      <p><strong><i class="fas fa-hammer"></i></strong> <%= result.searchable.category %></p>
                    </div>
                  </div>
                <% end %>
              <% end %>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<!--
<h1>Careers#index</h1>
<p>Find me in app/views/careers/index.html.erb</p> -->
 <!-- Begin Page Content -->
        <!-- <div class="container-fluid">
 -->
          <!-- Page Heading -->
          <!-- <h1 class="h3 mb-2 text-gray-800">Tables</h1>
          <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below. For more information about DataTables, please visit the <a target="_blank" href="https://datatables.net">official DataTables documentation</a>.</p> -->

          <!-- DataTales Example -->
          <!-- <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Position</th>
                      <th>Office</th>
                      <th>Age</th>
                      <th>Start date</th>
                      <th>Salary</th>
                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                      <th>Name</th>
                      <th>Position</th>
                      <th>Office</th>
                      <th>Age</th>
                      <th>Start date</th>
                      <th>Salary</th>
                    </tr>
                  </tfoot>
                  <tbody>
                    <tr>
                      <td>Tiger Nixon</td>
                      <td>System Architect</td>
                      <td>Edinburgh</td>
                      <td>61</td>
                      <td>2011/04/25</td>
                      <td>$320,800</td>
                    </tr>
                    <tr>
                      <td>Garrett Winters</td>
                      <td>Accountant</td>
                      <td>Tokyo</td>
                      <td>63</td>
                      <td>2011/07/25</td>
                      <td>$170,750</td>
                    </tr>
                    <tr>
                      <td>Ashton Cox</td>
                      <td>Junior Technical Author</td>
                      <td>San Francisco</td>
                      <td>66</td>
                      <td>2009/01/12</td>
                      <td>$86,000</td>
                    </tr>
                    <tr>
                      <td>Cedric Kelly</td>
                      <td>Senior Javascript Developer</td>
                      <td>Edinburgh</td>
                      <td>22</td>
                      <td>2012/03/29</td>
                      <td>$433,060</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>

        </div> -->
        <!-- /.container-fluid -->

 <!--      </div> -->
      <!-- End of Main Content -->

app/views/careers/index2.html.erb
<h1>Careers#index</h1>
<p>Find me in app/views/careers/index.html.erb</p>
 <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-2 text-gray-800">Tables</h1>
          <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below. For more information about DataTables, please visit the <a target="_blank" href="https://datatables.net">official DataTables documentation</a>.</p>

          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Position</th>
                      <th>Office</th>
                      <th>Age</th>
                      <th>Start date</th>
                      <th>Salary</th>
                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                      <th>Name</th>
                      <th>Position</th>
                      <th>Office</th>
                      <th>Age</th>
                      <th>Start date</th>
                      <th>Salary</th>
                    </tr>
                  </tfoot>
                  <tbody>
                    <tr>
                      <td>Tiger Nixon</td>
                      <td>System Architect</td>
                      <td>Edinburgh</td>
                      <td>61</td>
                      <td>2011/04/25</td>
                      <td>$320,800</td>
                    </tr>
                    <tr>
                      <td>Garrett Winters</td>
                      <td>Accountant</td>
                      <td>Tokyo</td>
                      <td>63</td>
                      <td>2011/07/25</td>
                      <td>$170,750</td>
                    </tr>
                    <tr>
                      <td>Ashton Cox</td>
                      <td>Junior Technical Author</td>
                      <td>San Francisco</td>
                      <td>66</td>
                      <td>2009/01/12</td>
                      <td>$86,000</td>
                    </tr>
                    <tr>
                      <td>Cedric Kelly</td>
                      <td>Senior Javascript Developer</td>
                      <td>Edinburgh</td>
                      <td>22</td>
                      <td>2012/03/29</td>
                      <td>$433,060</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->