config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # resources :dashboards, only: [:show, :update]

  get "dashboards/:user_id", to: "dashboards#show", as: "dashboard"
  get 'users_personnalities/:user_id', to: "users_personnalities#show", as: "results"
  resources :users_personnalities, only: :create
  root to: 'pages#home'
  # resources :surveys, only: [:index, :show]
  resources :answers, only: [] do
    resources :users_answers, only: [:create]
  end
  resources :careers, only: [:index]
  resources :surveys, only: [:index, :show] do
    resources :attempts, only: [:new, :create, :edit, :update]
  end

  resources :training_centers, only: [:index, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attempt.rb
class Attempt < ApplicationRecord
  belongs_to :survey
  belongs_to :user
  has_many :user_answers, dependent: :destroy
end

app/models/career.rb
class Career < ApplicationRecord
  belongs_to :personality_riasec
  has_many :training_centers, dependent: :destroy
  has_many :users_personalities
  include PgSearch
  multisearchable against: [:title, :category]
  scope :find_title, lambda { |search| where("title ILIKE :search", search: "%#{search}%") }
end

app/models/global_search.rb
class GlobalSearch

  def initialize(query)
    @query = query
  end

  def result_careers
    Career.search(query)
  end

  def result_training_centers
    TrainingCenter.search(query)
  end
end

app/models/personality_riasec.rb
class PersonalityRiasec < ApplicationRecord
  has_many :success_profiles
  has_many :careers, dependent: :destroy
  has_many :users_personalities
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey
  has_many :answers, dependent: :destroy
end

app/models/success_profile.rb
class SuccessProfile < ApplicationRecord
  belongs_to :personalityriasec
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :attempts, dependent: :destroy
  has_many :questions, dependent: :destroy
end

app/models/training_center.rb
class TrainingCenter < ApplicationRecord
  belongs_to :career
  include PgSearch
  multisearchable against: [:name, :city, :category]
  scope :find_name, lambda { |search| where("name ILIKE :search", search: "%#{search}%") }
  geocoded_by :full_address
  # mount_uploader :photo, PhotoUploader
  after_validation :geocode, if: :will_save_change_to_full_address?

  def full_address
    [address, postal_code, city].compact.join(', ')
  end

  def will_save_change_to_full_address?
    will_save_change_to_address? || will_save_change_to_postal_code? || will_save_change_to_city?
  end

  private

  def training_params
    params.require(:training_centersin).permit(:photo)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :photo, PhotoUploader
  has_many :user_answers, dependent: :destroy
  has_many :attempts, dependent: :destroy
  has_many :users_personalities, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  # after_create :send_welcome_email

    #private

    #def send_welcome_email
    # UserMailer.welcome(self).deliver_now
    #end
end

app/models/user_answer.rb
class UserAnswer < ApplicationRecord
  belongs_to :answer
  belongs_to :user
  belongs_to :attempt
end

app/models/users_personality.rb
class UsersPersonality < ApplicationRecord
  belongs_to :user
  belongs_to :career, optional: true
  belongs_to :personalityriasec, optional: true
end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController
  def new
    @survey = Survey.find(params[:survey_id])
    @attempt = Attempt.create(user: current_user, survey: @survey, result: "")
    @questions = @survey.questions.where(gender: [nil, current_user.gender])
    @lastquestion = @questions.find_by(number: 8)
  end

  def update
    @attempt = Attempt.find(params[:id])
    @user = current_user
    @user_answer = UserAnswer.all.where(user_id: @user)
    @user_answers = @user_answer.where(attempt_id: @attempt)
    @user_answers.each do |answer|
      @attempt.result << answer.answer.column
    end
    calcul = []
    r = @attempt.result.count("R")
    calcul << r
    i = @attempt.result.count("I")
    calcul << i
    a = @attempt.result.count("A")
    calcul << a
    s = @attempt.result.count("S")
    calcul << s
    e = @attempt.result.count("E")
    calcul << e
    c = @attempt.result.count("C")
    calcul << c
    case calcul.max
    when calcul[0]
      result = "R"
    when calcul[1]
      result = "I"
    when calcul[2]
      result = "A"
    when calcul[3]
      result = "S"
    when calcul[4]
      result = "E"
    when calcul[5]
      result = "C"
    end
    @attempt.update(result: result)
    redirect_to results_path(current_user)
  end
end

app/controllers/careers_controller.rb
class CareersController < ApplicationController
  def index
    @careers = Career.all
    @user = current_user
    @user_personality = UsersPersonality.find_by(user_id: current_user)
    @results = PgSearch.multisearch(params[:query])
  end

  def show
    @career = Career.find(params[:id])
    @users_personalities = @career.users_personalities.where(gender: [nil, current_user.gender])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def index
    @surveys = Survey.all
  end

  def show
    @survey = Survey.find(params[:id])
    @questions = @survey.questions.where(gender: [nil, current_user.gender])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    # To uncomment when other tables will be created.
    # @training_centers = current_user.users_personalities.training_centers.where.not(latitude: nil, longitude: nil)

    # @markers = @training_centers.map do |training_center|
    #   {
    #     lng: training_center.longitude,
    #     lat: training_center.latitude
    #   }
    # end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag asset_path('logo-icon.png') %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

  </body>

</html>

app/views/pages/home.html.erb
<%= render 'shared/sidebar_menu' %>
<!-- Full Page Image Header with Vertically Centered Content -->
<header class="masthead-img animated--fade-in clearfix" style="background-image: linear-gradient(rgba(0, 0, 0, 0.35), rgba(0, 0, 0, 0.35)), url(<%= image_path "mountain-climber-home.jpg", alt: "mountain climber homepage" %>);">
  <div class="container h-100 bg-overlay">
    <div class="row h-100 align-items-center">
      <div class="col-12 text-center">
          <!-- Logo -->
        <%= link_to root_path do %>
          <%= image_tag "logo-reecover-transparent-white.png", height: 120 %>
        <% end %>
        <h1><strong>Votre carrière a de la valeur</strong></h1>
        <hr class="col-6">
        <h4>Sportifs en reconversion, vous souhaitez donner un nouvel élan à votre carrière ?
        </h4>
        <br><br>
        <a href="#test-riasec" class="btn btn-warning btn-lg">Comment ça marche ?</a>
        <%= link_to "Faites le test !", new_survey_attempt_path(Survey.last), class: "btn btn-warning btn-lg"  %>
        </div>
    </div>
  </div>
</header>
  <!-- Header -->

<section class="py-5 clearfix" id="test-riasec">
  <div class="container mt-5">
    <div class="row">
      <div class="col-md-7">
        <h2><strong>Qu'est-ce que la typologie de Holland (RIASEC) ?</strong></h2>
        <hr>
        <p>La typologie de Holland, appelée couramment <strong>RIASEC</strong>, permet d’explorer le monde du travail en <strong>se basant sur les caractéristiques personnelles (personnalité, aptitudes, intérêts, etc.)</strong> associées à chaque profession. John Holland reconnaît 6 types de personnalité :</p>
          <ol>
            <li><strong>Réaliste (R) :</strong> Besoin d'être impliqué physiquement dans ce qu'il fait.</li>
            <li><strong>Investigateur (I) :</strong> Habité par une soif de connaissances et de savoir.</li>
            <li><strong>Artistique (A) :</strong> Souhaite exprimer ses émotions ou pensées à travers des formes d'art.</li>
            <li><strong>Social (S) :</strong> Attiré par les activités favorisant le contact avec les autres, particulièrement dans le but de les aider.</li>
            <li><strong>Entreprenant (E) :</strong> Aime avoir des responsabilités, surmonter des défis dans l'espoir de se hisser au sommet.</li>
            <li><strong>Conventionnel (C) :</strong> Désire respecter les normes, consignes et règles.</li>
          </ol>
        <br>
        <%= link_to "Démarrer le test", new_survey_attempt_path(Survey.last), class: "btn btn-warning btn-lg"  %>

      </div>
    <div class="col-md-5" id="loading">
       <%= image_tag "riasec-personnalités.png", width: '100%', class: "img-fluid" %>
    </div>
  </div>
</div>
</section>



<section class="py-5 clearfix" id="test-riasec" style="background: lightgrey; margin-top: 60px;">
    <div class="container">
        <div class="row">
          <h2 class="col-md-12 text-center"><strong>De belles expériences de reconversion sportive réussie !</strong></h2>
          <hr>
          <!--Profile Card 3-->
        <div class="col-md-4 mt-5">
            <div class="card profile-card-3">
                <div class="background-block">
                    <img src="https://images.pexels.com/photos/459225/pexels-photo-459225.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"class="background"/>
                </div>
                <div class="profile-thumb-block">
                    <%= image_tag "lauraflessel.jpg", alt: "profile-image", class: "profile" %>
                </div>
                <div class="card-content">
                    <h2>Laura Flessel</h2>
                    <span class="badge badge-pill badge-warning">Entreprenant - Ministre</span>
                    <br>
                    <small>Escrimeuse</small>
                   <p class="card-text text-center small">La plus décorée des escrimeuses françaises est nommée Ministre des Sports en raison de son expérience dans le domaine sportif. </p>
                    </div>
                </div>
              </div>

                  <div class="col-md-4 mt-5">
            <div class="card profile-card-3">
                <div class="background-block">
                    <img src="https://images.pexels.com/photos/459225/pexels-photo-459225.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"class="background"/>
                </div>
                <div class="profile-thumb-block">
                    <%= image_tag "etchebest.jpg", alt: "profile-image", class: "profile" %>
                </div>
                <div class="card-content">
                    <h2>Philippe Etchebest</h2>
                    <span class="badge badge-pill badge-warning">Réaliste - Chef Cuisinier</span>
                    <br>
                    <small>Boxeur et Rugyman</small>
                   <p class="card-text text-center small">A établi un vrai parallèle entre son vécu en équipe sur le terrain, et sa vie avec son équipe en cuisine. L'état d'esprit est le même, les valeurs aussi.</p>
                    </div>
                </div>
              </div>

                  <div class="col-md-4 mt-5">
            <div class="card profile-card-3">
                <div class="background-block">
                    <img src="https://images.pexels.com/photos/459225/pexels-photo-459225.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"class="background"/>
                </div>
                <div class="profile-thumb-block">
                    <%= image_tag "lorie.jpg", alt: "profile-image", class: "profile" %>
                </div>
                <div class="card-content">
                    <h2>Lorie</h2>
                    <span class="badge badge-pill badge-warning">Artistique - Chanteuse</span>
                    <br>
                    <small>Patineuse artistique</small>
                   <p class="card-text text-center small">Sa carrière musicale a failli ne jamais voir le jour car la chanteuse se prédestinait au patinage artistique : une blessure l'a contrainte à tout arrêter.</p>
                    </div>
                </div>
              </div>
          </div>
    </div>
</section>
  <!--Section: Live preview-->

<%= render 'shared/footer' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <a class="scroll-to-top rounded" href="#">
    <i class="fas fa-angle-up"></i>
  </a>
<!-- Footer -->
<footer class="page-footer font-small special-color-dark pt-4 fixed-bottom">

    <!-- Footer Elements -->
    <div class="container">

      <!--Grid row-->
      <div class="row - text-center">
       <!-- Grid column -->
        <div class="col-md-12 py-1">
          <div class="mt-3 flex-center">

            <!-- Facebook -->
            <a class="social-ic">
              <i class="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-1x"> </i>
            </a>
            <!-- Twitter -->
            <a class="social-ic">
              <i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-1x"> </i>
            </a>
            <!-- Google +-->
            <a class="social-ic">
              <i class="fab fa-github fa-lg white-text mr-md-5 mr-3 fa-1x"> </i>
            </a>
            <!--Linkedin -->
            <a class="social-ic">
              <i class="fab fa-linkedin-in fa-lg white-text mr-md-5 mr-3 fa-1x"> </i>
            </a>
            <!--Instagram-->
            <a class="social-ic">
              <i class="fab fa-instagram fa-lg white-text mr-md-5 mr-3 fa-1x"> </i>
            </a>
            <!--Pinterest-->
            <a class="social-ic">
              <i class="fab fa-pinterest fa-lg white-text fa-1x"> </i>
            </a>
          </div>
        </div>
        <!-- Grid column -->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!-- Form -->
<!--           <form class="form-inline">
            <input class="form-control form-control-sm mr-3 w-75" type="text" placeholder="Search" aria-label="Search">
            <i class="fas fa-search" aria-hidden="true"></i>
          </form> -->
          <!-- Form -->

      </div>
        <!--Grid column-->

        <!--Grid column-->
<!--         <div class="col-md-6 mb-4">

          <form class="input-group">
            <input type="text" class="form-control form-control-sm" placeholder="Your email" aria-label="Your email" aria-describedby="basic-addon2">
            <div class="input-group-append">
              <button class="btn btn-sm btn-outline-white my-0" type="button">Sign up</button>
            </div>
          </form>

        </div> -->
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
    <!-- Footer Elements -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2019 Copyright :
      Reecover Dream Team <i class="fas fa-heart"></i> at Le Wagon
    </div>
    <!-- Copyright -->

  </footer>
  <!-- Footer -->

app/views/shared/_navbar.html.erb
<div class="navbar-wagon fixed-top">

  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo-reecover-transparent-white.png", height: 100 %>
  <% end %>

      <div class="search-bar form-inline">
        <%= form_tag careers_path, method: :get do %>
          <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Trouver une formation "
          %>
          <%= button_tag "", class: "btn fas fa-search fa-sm btn-lg" %>
        <% end %>
      </div>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <% if params[:controller] === "dashboards" %>
        <button type="button" id="sidebarCollapse" class="btn">
          <i class="fas fa-align-left"></i>
        </button>
        <% else %>
      <% end %>

        <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to dashboard_path(current_user) do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Dashboard") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Se déconnecter") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "btn btn-success" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
         <li>
              <%= link_to edit_user_registration_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to dashboard_path(current_user) do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Dashboard") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Se déconnecter") %>
              <% end %>
            </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_sidebar_menu.html.erb
  <!-- Navigation -->
  <a class="menu-toggle rounded" href="#">
    <i class="fas fa-bars fa-2x"></i>
  </a>
  <nav id="sidebar-wrapper">
  <% if user_signed_in? %>

      <!-- Links when logged in -->
     <!--  <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %> -->
      <% if params[:controller] === "dashboards" %>
        <button type="button" id="sidebarCollapse" class="btn btn-info">
          <i class="fas fa-align-left"></i>
          <span>Dashboard</span>
        </button>
        <% else %>
      <% end %>
    <ul class="sidebar-nav sidebar-brand">
       <%= cl_image_tag current_user.photo, class: "avatar-dashbord", id: "navbar-wagon-menu" %>
       <li class="sidebar-nav-item">
        <%= link_to root_path 'Accueil' do %>
        <i class="fas fa-home"></i>   Accueil
        <% end %>
      </li>
      <li class="sidebar-nav-item">
        <%= link_to dashboard_path(current_user) do %>
                <i class="fas fa-user"></i> <%= t(".profile", default: "Mon compte") %>
              <% end %>
      </li>
        <li class="sidebar-nav-item">
        <%= link_to new_survey_attempt_path(Survey.last) do %>
                <i class="fas fa-poll-h"></i> <%= t(".profile", default: "Test RIASEC") %>
              <% end %>
      </li>
       <li class="sidebar-nav-item">
        <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Se déconnecter") %>
         <% end %>
            </li>
    <% else %>
    </ul>
    <ul class="sidebar-nav sidebar-brand">
        <!--/. Logo -->
          <hr>
      <li class="sidebar-nav-item">
        <!-- Login link (when logged out) -->
         <%= link_to new_user_session_path do %>
         <i class="fas fa-sign-in-alt"></i> <%= t(".sign_in", default: "Se connecter") %>
         <% end %>
          </li>
        <li class="sidebar-nav-item">
         <%= link_to new_user_registration_path do %>
         <i class="fas fa-user"></i> <%= t(".sign_up", default: "Créer mon compte") %>
         <% end %>
          </li>
        <% end %>
    </ul>
  </nav>