config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # resources :dashboards, only: [:show, :update]

  get "dashboards/:user_id", to: "dashboards#show", as: "dashboard"
  get 'users_personnalities/:user_id', to: "users_personnalities#show", as: "results"
  resources :users_personnalities, only: :create
  root to: 'pages#home'
  # resources :surveys, only: [:index, :show]
  resources :answers, only: [] do
    resources :users_answers, only: [:create]
  end
  resources :careers, only: [:index]
  resources :surveys, only: [:index, :show] do
    resources :attempts, only: [:new, :create, :edit, :update]
  end

  resources :training_centers, only: [:index, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attempt.rb
class Attempt < ApplicationRecord
  belongs_to :survey
  belongs_to :user
  has_many :user_answers, dependent: :destroy
end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController
  def new
    @survey = Survey.find(params[:survey_id])
    @attempt = Attempt.create(user: current_user, survey: @survey, result: "")
    @questions = @survey.questions.where(gender: [nil, current_user.gender])
    @lastquestion = @questions.find_by(number: 8)
  end

  def update
    @attempt = Attempt.find(params[:id])
    @user = current_user
    @user_answer = UserAnswer.all.where(user_id: @user)
    @user_answers = @user_answer.where(attempt_id: @attempt)
    @user_answers.each do |answer|
      @attempt.result << answer.answer.column
    end
    calcul = []
    r = @attempt.result.count("R")
    calcul << r
    i = @attempt.result.count("I")
    calcul << i
    a = @attempt.result.count("A")
    calcul << a
    s = @attempt.result.count("S")
    calcul << s
    e = @attempt.result.count("E")
    calcul << e
    c = @attempt.result.count("C")
    calcul << c
    case calcul.max
    when calcul[0]
      result = "R"
    when calcul[1]
      result = "I"
    when calcul[2]
      result = "A"
    when calcul[3]
      result = "S"
    when calcul[4]
      result = "E"
    when calcul[5]
      result = "C"
    end
    @attempt.update(result: result)
    redirect_to results_path(current_user)
  end
end

app/views/attempts/new.html.erb
<%= render 'shared/sidebar_menu' %>
<!-- @answers[1].photo -->
<div data-container="0" class="animated--fade-in">
<header class="masthead-img" style="background-image: linear-gradient(rgba(0, 0, 0, 0.35), rgba(0, 0, 0, 0.35)), url(<%= image_path "skateboard-survey-light.jpg", alt: "skateboard background survey" %>);">
    <div class="row h-100 align-items-center">
      <div class="col-12 text-center">
          <!-- Logo -->
        <%= link_to root_path do %>
          <%= image_tag "logo-reecover-transparent-white.png", height: 120 %>
        <% end %>
        <h1><strong>Votre carrière a de la valeur</strong></h1>
        <hr class="col-4">
        <h4>Pour quels métiers êtes-vous fait ? Trouvez votre vocation en fonction de vos affinités.
        </h4>
        <br><br>
        <div class="o-section-home__select-gender m-select-gender">

            <!-- button gender male-->
            <div data-button class="a-button-gender">
                <div class="a-button-gender__content">
                  <div class="a-button-gender__text"> <%= image_tag "male-athlete.jpg", class: "img-gender pulse-button" %><br><strong>Sportif</strong></div>
                </div>
            </div>

          <div class="m-select-gender__text">ou</div>

          <!-- button gender female-->
          <div data-button class="a-button-gender">
              <div class="a-button-gender__content">
                  <div class="a-button-gender__text"> <%= image_tag "female-athlete.jpg", class: "img-gender-f pulse-button" %><br><strong>Sportive</strong></div>
              </div>
            </div>

          </div>
      </div>
    </div>
  </div>
</header>
  <!-- Header -->
  <div class="container-quiz">
    <% @questions.each do |question| %>
<!--             if question == @questions.last
          redirect_to sss_path -->
    <div data-container="<%= question.number %>">
      <div class="overlay" id="question-<%= question.number %>" data-question="<%= question.number %>"><h2 class="text-center mb-5"> <%= question.question %> </h2></div>
        <div class="cards-quiz">
          <div class="row-questions align-items-start text-center">
          <% question.answers.each_with_index do |answer, index| %>
            <div class="col-xs-6 col-md-6 col-lg-4 card-custom">
              <%= link_to answer_users_answers_path(answer), method: :post, remote: @questions.last != question do %>
                <div class="card-category-quiz" id="card-answer" style="background-image: linear-gradient(rgba(0,0,0,0.25), rgba(0,0,0,0.25)), url('<%= image_url(answer.photo)%>'); transition-delay: <%= index/5.1 %>s ">
                 <strong> <%= answer.answer %></strong>
                </div>
              <% end %>
            </div>
          <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <!-- Show results -->
<header class="masthead-results">
  <div class="container h-100 bg-overlay">
    <div class="row h-100 align-items-center justify-content-center">
      <div class="col-7 text-center">
        <h1><strong>Pour quels métiers êtes-vous fait ?</strong></h1>
        <hr class="col-6">
        <br><br>
          <div id="question-<%= @questions.last.id + 1 %>" data-question="9" data-container="9">
            <!-- BOUTON TEST -->
<center>
  <%= link_to "Voir les résultats", survey_attempt_path(Survey.last.id, Attempt.last.id), method: :patch, class: "btn btn-warning btn-lg"  %>
</center>